### ISSUE TITLE
Linking the Saved Drafts/ Download Page to the backend

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#113]

**Comment by jolomi212** [comment]
Work on this has been ongoing on the auth_gen_conv_backend branch https://github.com/zuri-training/Team-64_Favicon-Gen/tree/auth_gen_conv_backend

**Comment by jolomi212** [comment]
I worked together with Hermann Wakam @WakHerv7  on linking the saved drafts page to the backend, using django. We were able to fetch saved drafts from the database models for each user, and display them on the front end, so that the user can download.
 Our work in this regard was mostly pushed to this branch: https://github.com/zuri-training/Team-64_Favicon-Gen/tree/auth_gen_conv_backend The multiple commits made on this task are available here: https://github.com/zuri-training/Team-64_Favicon-Gen/commits/auth_gen_conv_backend
